agmiweb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sermon.urls')),
]
    


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

sermon/urls.py
from django.urls import path

from . import views

app_name = 'sermon'

urlpatterns = [
    path('',views.index,name='index'),
    path('event/',views.event, name = 'event'),
    path('about/',views.about, name = 'about'),
    path('blog/',views.blog, name = 'blog'),
]

sermon/models.py
from django.db import models

# Create your models here.
class Sermon(models.Model):
    title = models.CharField(max_length=100)
    author_name = models.CharField(max_length=100)
    date = models.DateField()
    photo = models.FileField()
    file = models.FileField()

    def __str__(self):
        return self.title

class Event(models.Model):
    title = models.CharField(max_length=100)
    date = models.DateField()
    time = models.TimeField()
    venue = models.CharField(max_length=100)
    aboutEvent = models.CharField(max_length=1000)
    photo = models.FileField()

    def __str__(self):
        return self.title

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.CharField(max_length=3000)
    photo = models.FileField()
    author = models.CharField(max_length= 30)
    date = models.DateField()

    def __str__(self):
        return self.title

sermon/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from django.template import loader
from django.views import generic
from . models import Sermon, Event, Post

def index(request):
    template = loader.get_template('sermon/index.html')
    sermons = Sermon.objects.all()
    context ={
        'sermons' : sermons
    }
    return HttpResponse(template.render(context,request))

def event(request):
    template = loader.get_template('sermon/event.html')
    events = Event.objects.all()
    context = {
        'events':events
    }
    return HttpResponse(template.render(context,request))

def about(request):
    template = loader.get_template('sermon/about.html')
    context = {}
    return HttpResponse(template.render(context,request))

def blog(request):
    template = loader.get_template('sermon/blog.html')
    posts = Post.objects.all()
    context = {
        'posts': posts
    }
    return HttpResponse(template.render(context,request))

sermon/templates/sermon/Event.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">


    <!--Import Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="../../static/sermon/css/materialize.min.css" media="screen,projection" />
    <!-- My styles -->
    <link type="text/css" rel="stylesheet" href="../../static/sermon/css/style.css" media="screen,projection" />

    <title>Document</title>
</head>

<body>
    <div class="event-header">
        <div class="tinth">
            <h4 class="event-title white-text">Events</h4>
        </div>
        <div>
            <div class="navbar-fixed">
                <nav class="nav-wrapper z-depth-0 transparent">
                    <div class="nav-container">
                        <a href="#" class="brand-logo left"><img src="../../static/sermon/Images/logo.jpg" alt="" class="responsive-img"></a>
                        <a href="#" data-target="mobile-menu" class="sidenav-trigger right">
                            <i class="material-icons blue-text">menu</i>
                        </a>
                        <ul class="hide-on-med-and-down right">
                            <li><a href="{% url 'sermon:index'%}">Home</a></li>
                            <li><a href="{% url 'sermon:about'%}">About</a></li>
                            <li><a href="#">Events</a></li>
                            <li><a href="#">Sermons</a></li>
                            <li><a href="{% url 'sermon:blog'%}">Blog</a></li>
                            <li><a href="#">Contact</a></li>
                        </ul>
                    </div>

                </nav>
                
            </div>
        </div>

        <ul class="sidenav right" id="mobile-menu">
            <li><a href="#">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Events</a></li>
            <li><a href="#">Library</a></li>
            <li><a href="#">Contact</a></li>
        </ul>

    </div>


    <div class="pad-top">
        <div class="container">
            {% if events%}
            {% for event in events%}

            <div class="row">
                <div class="col s12 m6 l6">
                    <img src="{{event.photo.url}}" alt="" class="responsive-img">
                </div>
                <div class="col s12 m6 l6">
                    <h4>{{event.title}}</h4>
                    Date: {{event.date}} <br>
                    Address: {{event.venue}} <br>
                    Time: {{event.time}} &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="" class="btn blue white-text">Detail</a>
                </div>
            </div>

            {%endfor%}
            {%else%}
            <h2>No Events</h2>
            {%endif%}
        </div>

    </div>



    <footer class="page-footer">
        <div class="container">
            <div class="row">
                <div class="col s12 l6">
                    <h5>Subscribe to Our newsletter</h5>
                    <form action="">
                        <div class="input-field">
                            <input type="email" id="email">
                            <label for="email">Email</label>
                        </div>
                        <div class="input-field">
                            <input type="submit" value="Submit" class="btn orange">
                        </div>
                    </form>
                </div>
                <div class="col s12 l6">
                    <h5>Connect with us</h5>
                    <a href="#">Facebook</a><br>
                    <a href="#">Twitter</a><br>
                    <a href="#">Instagram</a><br>

                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container center-align">
                copyright &copy; 2019 AGMI Media
            </div>
        </div>
    </footer>

    <script src="../../static/sermon/js/materialize.min.js"></script>
    <script>
        // sidenav
        const sideNav = document.querySelector('.sidenav');
        M.Sidenav.init(sideNav, {});
        //slider
        const slider = document.querySelector('.slider');
        M.Slider.init(slider, {
            indicators: false,
            height: 550,
            transition: 500,
            interval: 5000

        });
        const parallax = document.querySelector('.parallax');
        M.Parallax.init(parallax, {

        });
    </script>
</body>

</html>

sermon/templates/sermon/about.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">


    <!--Import Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="../../static/sermon/css/materialize.min.css" media="screen,projection" />
    <!-- My styles -->
    <link type="text/css" rel="stylesheet" href="../../static/sermon/css/style.css" media="screen,projection" />

    <title>Document</title>
</head>

<body>
    <div class="event-header">
        <div class="tinth">
            <h4 class="event-title white-text">About</h4>
        </div>
        <div>
            <div class="navbar-fixed">
                <nav class="nav-wrapper z-depth-0 transparent">
                    <div class="nav-container">
                        <a href="#" class="brand-logo left"><img src="../../static/sermon/Images/logo.jpg" alt="" class="responsive-img"></a>
                        <a href="#" data-target="mobile-menu" class="sidenav-trigger right">
                            <i class="material-icons blue-text">menu</i>
                        </a>
                        <ul class="hide-on-med-and-down right">
                            <li><a href="{% url 'sermon:index'%}">Home</a></li>
                            <li><a href="#">About</a></li>
                            <li><a href="{% url 'sermon:event'%}">Events</a></li>
                            <li><a href="#">Sermons</a></li>
                            <li><a href="{% url 'sermon:blog'%}">Blog</a></li>
                            <li><a href="#">Contact</a></li>
                        </ul>
                    </div>

                </nav>
                
            </div>
        </div>

        <ul class="sidenav right" id="mobile-menu">
            <li><a href="{% url 'sermon:index'%}">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="{% url 'sermon:event'%}">Events</a></li>
            <li><a href="#">Sermons</a></li>
            <li><a href="#">Blog</a></li>
            <li><a href="#">Contact</a></li>
        </ul>

    </div>

    <div class="about">
            <div class="container">
                    <p>
                        AGMI is a Non-Denominational ministry; it is an Apostolic, evangelistic and a Teaching
                        ministry which started officially on 8th February, 2015 in the city of Jos.<br>
            
                        The ministry began after the Lord specifically spoke to our set-man,
                        Dr. Luka Satlong King on the 25th of March, 2014 while he was praying in the morning.
                    </p>
                </div>
    </div>
  



    <footer class="page-footer">
        <div class="container">
            <div class="row">
                <div class="col s12 l6">
                    <h5>Subscribe to Our newsletter</h5>
                    <form action="">
                        <div class="input-field">
                            <input type="email" id="email">
                            <label for="email">Email</label>
                        </div>
                        <div class="input-field">
                            <input type="submit" value="Submit" class="btn orange">
                        </div>
                    </form>
                </div>
                <div class="col s12 l6">
                    <h5>Connect with us</h5>
                    <a href="#">Facebook</a><br>
                    <a href="#">Twitter</a><br>
                    <a href="#">Instagram</a><br>

                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container center-align">
                copyright &copy; 2019 AGMI Media
            </div>
        </div>
    </footer>

    <script src="../../static/sermon/js/materialize.min.js"></script>
    <script>
        // sidenav
        const sideNav = document.querySelector('.sidenav');
        M.Sidenav.init(sideNav, {});
        //slider
        const slider = document.querySelector('.slider');
        M.Slider.init(slider, {
            indicators: false,
            height: 550,
            transition: 500,
            interval: 5000

        });
        const parallax = document.querySelector('.parallax');
        M.Parallax.init(parallax, {

        });
    </script>
</body>

</html>

sermon/templates/sermon/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!--Import Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="../../static/sermon/css/materialize.min.css"
        media="screen,projection" />
    <!-- My styles -->
    <link type="text/css" rel="stylesheet" href="../../static/sermon/css/style.css" media="screen,projection" />
    <!-- owl-carousel -->
    <link type="text/css" rel="stylesheet" href="../../static/sermon/css/owl.carousel.min.css"
        media="screen,projection" />
    <link type="text/css" rel="stylesheet" href="../../static/sermon/css/owl.theme.default.min.css"
        media="screen,projection" />

    <title>AGMI</title>
</head>

<body>

    <header>
        <div class="tint-head hide-on-small-only"></div>
        <div class="tint-head1 hide-on-med-and-up"></div>
        <div>
            <div class="navbar-fixed">
                <nav class="nav-wrapper z-depth-0 transparent">
                    <div class="nav-container">
                        <a href="#" class="brand-logo left"><img src="../../static/sermon/Images/logo.jpg" alt=""
                                class="responsive-img"></a>
                        <a href="#" data-target="mobile-menu" class="sidenav-trigger right">
                            <i class="material-icons white-text">menu</i>
                        </a>
                        <ul class="hide-on-med-and-down right">
                            <li><a href="#">Home</a></li>
                            <li><a href="{% url 'sermon:about'%}">About</a></li>
                            <li><a href="{% url 'sermon:event'%}">Events</a></li>
                            <li><a href="#">Sermons</a></li>
                            <li><a href="{% url 'sermon:blog'%}">Blog</a></li>
                            <li><a href="#">Contact</a></li>
                        </ul>
                    </div>

                </nav>
                <div class="caption">
                    <p class="hide-on-small-only">
                        ... raising a people of Glory and Absolute Dominion
                    </p>
                </div>
                <div class="center">
                    <div class="caption1">
                        <p class="hide-on-med-and-up">
                            Absolute Dominion
                        </p>
                    </div>
                </div>
            </div>


        </div>


        <ul class="sidenav right" id="mobile-menu">
            <li><a href="#">Home</a></li>
            <li><a href="{% url 'sermon:about'%}">About</a></li>
            <li><a href="{% url 'sermon:event'%}">Events</a></li>
            <li><a href="#">Library</a></li>
            <li><a href="#">Contact</a></li>
        </ul>
    </header>
    <div class="count-down">

        <div class="row">
            <div class="col s12 m4 l4">
                <h5 class="white-text">Upcoming Event</h5>
                <p class="white-text">
                    <h3 class="white-text">Kingdom Wealth Summit</h3> 
                    
                </p>
            </div>

            <div class="col s12 m8 l8">
                <div class="row">
                    <div class="col s3 m3 l3 white-text">
                        <h3 id="day">13</h3>days
                    </div>
                    <div class="col s3 m3 l3 white-text">
                        <h3 id="hour">24</h3>hours
                    </div>
                    <div class="col s3 m3 l3 white-text">
                        <h3 id="minute">56</h3>minutes
                    </div>
                    <div class="col s3 m3 l3 white-text">
                        <h3 id="second">13</h3>seconds
                    </div>
                </div>


            </div>
        </div>

    </div>

    <div class="space">

    </div>

    <div class="container">
        <div class="row">
            <div class="title">
                <h4 class="center">OUR MISSION</h4>
            </div>
            <div class="col s12 l4 m6">
                <img src="../../static/sermon/Images/about.jpg" alt="" class="responsive-img">
            </div>
            <div class="col s12 l8 m6">

                <p>
                    AGMI is a Non-Denominational ministry; it is an Apostolic, evangelistic and a Teaching
                    ministry which started officially on 8th February, 2015 in the city of Jos.<br>
        
                    The ministry began after the Lord specifically spoke to our set-man,
                    Dr. Luka Satlong King on the 25th of March, 2014 while he was praying in the morning.
                </p>
                <a href="{% url 'sermon:about'%}">Read more></a>
            </div>




        </div>

        <div class="row">
            <div class="title">
                <h4 class="center">OUR VISION</h4>
            </div>
            <div class="col s12 l4 m6 push-l8">
                <img src="../../static/sermon/Images/about.jpg" alt="" class="responsive-img">
            </div>
            <div class="col s12 l8 m6 pull-l4">

                <p>
                    AGMI is a Non-Denominational ministry; it is an Apostolic, evangelistic and a Teaching
                    ministry which started officially on 8th February, 2015 in the city of Jos.<br>
        
                    The ministry began after the Lord specifically spoke to our set-man,
                    Dr. Luka Satlong King on the 25th of March, 2014 while he was praying in the morning.
                </p>

                <a href="{% url 'sermon:about'%}">Read more></a>
            </div>




        </div>
    </div>



    <!-- <div class="parallax-container">
        <div class="tint hide-on-med-and-down">

        </div>

        <div class="parallax">
            <img src="../../static/sermon/Images/Untitled-3.jpg" alt="" class="responsive-img">
        </div>
    </div> -->
    <div class="custom-parallax">
        <div class="tint-head1">


        </div>
        <div class="container center-align">
            <h3 class="center custom-text">
                RECENT MESSAGES
            </h3>
        </div>
    </div>
    <div class="container">

    </div>

    <div class="container-custom">
        <div class="row">
            <div class="owl-carousel owl-theme">
                {% for sermon in sermons%}
               
                    <div class="card z-depth-0">
                        <div class="card-image">
                            <img src="{{sermon.photo.url}}" alt="" class="responsive-img">
    
                        </div>
                        <div class="card-content">
                            <span class="card-title">
                                <b>
                                    <h6>{{sermon.title}}</h6>
                                </b>
                            </span>
                            <p>
                                Apostle Luka Satlong
                            </p>
                            <a href="#" class=" btn-floating white z-depth-0">
                                <i class="material-icons blue-text">save</i>
                            </a>
                            <button class="btn-floating white z-depth-0" onclick="playAudio('{{sermon.file.url}}')">
                                <i>
                                    <img src="../../static/sermon/Images//play.png" alt="">
                                </i>
                            </button>
    
    
                        </div>
    
                    </div>
                
    
                {% endfor %}
            </div>
    
        </div>
    </div>

    <footer class="page-footer">
        <div class="container">
            <div class="row">
                <div class="col s12 m6 l6">
                    <h5>Subscribe to Our newsletter</h5>
                    <form action="">
                        <div class="input-field">
                            <input type="email" id="email">
                            <label for="email">Email</label>
                        </div>
                        <div class="input-field">
                            <input type="submit" value="Submit" class="btn orange">
                        </div>
                    </form>
                </div>
                <div class="col s12 m6 l6">
                    <h5>Connect with us</h5>
                    <a href="#">Facebook</a><br>
                    <a href="#">Twitter</a><br>
                    <a href="#">Instagram</a><br>

                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container center-align">
                copyright &copy; 2019 AGMI Media
            </div>
        </div>
    </footer>

    <script src="../../static/sermon/js/materialize.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="../../static/sermon/js/owl.carousel.min.js"></script>
    <script type="text/javascript" src="../../static/sermon/js/main.js"></script>
    <script type="text/javascript">
        //countdown
        function countdown() {
            var currentDate = new Date();
            var eventDate = new Date(2019, 6, 8);

            var currentTime = currentDate.getTime();
            var eventTime = eventDate.getTime();

            var timeLeft = eventTime - currentTime;

            var second = Math.floor(timeLeft / 1000);
            var minute = Math.floor(second / 60);
            var hour = Math.floor(minute / 60);
            var day = Math.floor(hour / 24);

            hour = hour%24;
            minute = minute%60;
            second = second%60;

            if(hour<10){
                hour = "0"+hour;
            }
            if(minute<10){
                minute = "0"+minute;
            }
            if(second<10){
                second = "0"+second;
            }

            document.getElementById("day").innerText = day;
            document.getElementById("hour").innerText = hour;
            document.getElementById("minute").innerText = minute;
            document.getElementById("second").innerText = second;
            
           
            setTimeout(countdown, 1000);
        }
        countdown();
    </script>
</body>

</html>

sermon/templates/sermon/stream.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!--Import Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="../../static/sermon/css/materialize.min.css"
        media="screen,projection" />
    <!-- My styles -->
    <link type="text/css" rel="stylesheet" href="../../static/sermon/css/style.css" media="screen,projection" />
    <!-- owl-carousel -->
    <link type="text/css" rel="stylesheet" href="../../static/sermon/css/owl.carousel.min.css"
        media="screen,projection" />
    <link type="text/css" rel="stylesheet" href="../../static/sermon/css/owl.theme.default.min.css"
        media="screen,projection" />

    <title>Document</title>
</head>
<body>
    <header>
        <div class="tint-head hide-on-small-only"></div>
        <div class="tint-head1 hide-on-med-and-up"></div>
        <div>
            <div class="navbar-fixed">
                <nav class="nav-wrapper z-depth-0 transparent">
                    <div class="nav-container">
                        <a href="#" class="brand-logo left"><img src="../../static/sermon/Images/logo.jpg" alt=""
                                class="responsive-img"></a>
                        <a href="#" data-target="mobile-menu" class="sidenav-trigger right">
                            <i class="material-icons white-text">menu</i>
                        </a>
                        <ul class="hide-on-med-and-down right">
                            <li><a href="#">Home</a></li>
                            <li><a href="{% url 'sermon:about'%}">About</a></li>
                            <li><a href="{% url 'sermon:event'%}">Events</a></li>
                            <li><a href="#">Sermons</a></li>
                            <li><a href="{% url 'sermon:blog'%}">Blog</a></li>
                            <li><a href="#">Contact</a></li>
                        </ul>
                    </div>

                </nav>
                <div class="caption">
                    <p class="hide-on-small-only">
                        ... raising a people of Glory and Absolute Dominion
                    </p>
                </div>
                <div class="center">
                    <div class="caption1">
                        <p class="hide-on-med-and-up">
                            Absolute Dominion
                        </p>
                    </div>
                </div>
            </div>


        </div>


        <ul class="sidenav right" id="mobile-menu">
            <li><a href="#">Home</a></li>
            <li><a href="{% url 'sermon:about'%}">About</a></li>
            <li><a href="{% url 'sermon:event'%}">Events</a></li>
            <li><a href="#">Library</a></li>
            <li><a href="#">Contact</a></li>
        </ul>
    </header>

    <footer class="page-footer">
        <div class="container">
            <div class="row">
                <div class="col s12 m6 l6">
                    <h5>Subscribe to Our newsletter</h5>
                    <form action="">
                        <div class="input-field">
                            <input type="email" id="email">
                            <label for="email">Email</label>
                        </div>
                        <div class="input-field">
                            <input type="submit" value="Submit" class="btn orange">
                        </div>
                    </form>
                </div>
                <div class="col s12 m6 l6">
                    <h5>Connect with us</h5>
                    <a href="#">Facebook</a><br>
                    <a href="#">Twitter</a><br>
                    <a href="#">Instagram</a><br>

                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container center-align">
                copyright &copy; 2019 AGMI Media
            </div>
        </div>
    </footer>

    <script src="../../static/sermon/js/materialize.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="../../static/sermon/js/owl.carousel.min.js"></script>
    <script type="text/javascript" src="../../static/sermon/js/main.js"></script>
</body>
</html>